In [9]:
import cv2,numpy,os

In [10]:
haar_file='harcascade_frontal_face.xml'

In [11]:
datasets='datasets'

In [12]:
(images,labels,names,id)=([],[],{},0)
face_cascade=cv2.CascadeClassifier(haar_file)

In [13]:
for (subdirs,dirs,files) in os.walk(datasets):
    for subdir in dirs:
        names[id]=subdir
        subjectpath=os.path.join(datasets,subdir)
        for filename in os.listdir(subjectpath):
            path=subjectpath+'/'+filename
            label=id
            images.append(cv2.imread(path,0))
            labels.append(int(label))
        id+=1
(width,height)=(130,100)
(images,labels)=[numpy.array(lis) for lis in [images,labels]]
print(images,labels)

[[[149 145 145 ... 140 150 153]
  [146 144 144 ... 142 151 152]
  [145 145 145 ... 146 150 154]
  ...
  [158 159 160 ... 223 224 223]
  [156 159 162 ... 219 224 222]
  [156 158 161 ... 214 215 212]]

 [[144 146 148 ... 133 148 152]
  [147 146 148 ... 128 144 153]
  [149 148 149 ... 124 145 153]
  ...
  [159 161 161 ... 220 218 219]
  [160 160 160 ... 213 215 208]
  [159 160 159 ... 199 202 201]]

 [[145 145 146 ... 154 156 155]
  [146 146 145 ... 151 156 157]
  [144 145 147 ... 150 154 157]
  ...
  [159 158 159 ... 201 200 198]
  [158 158 161 ... 200 200 199]
  [159 159 159 ... 198 200 199]]

 ...

 [[  1   0   0 ...   1   1   1]
  [  0   0   0 ...   1   1   0]
  [  0   0   0 ...   1   1   0]
  ...
  [  7   9  10 ...  15  19  15]
  [  9  10  10 ...  13  14  13]
  [ 11   9   9 ...  25  22  16]]

 [[  1   0   0 ...   1   1   1]
  [  0   0   0 ...   1   1   0]
  [  0   0   0 ...   1   1   0]
  ...
  [  7   9  10 ...  15  19  15]
  [  9  10  10 ...  13  14  13]
  [ 11   9   9 ...  25  22  

In [11]:
pip install opencv-contrib-python


  Using cached opencv_contrib_python-4.4.0.44-cp37-cp37m-win_amd64.whl (40.1 MB)
Note: you may need to restart the kernel to use updated packages.


ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\Dell\\anaconda\\Lib\\site-packages\\cv2\\cv2.cp37-win_amd64.pyd'
Consider using the `--user` option or check the permissions.



In [14]:
model=cv2.face.LBPHFaceRecognizer_create()

In [15]:
model.train(images,labels)
print("Training Completed")

Training Completed


In [ ]:
print("Training Completed")

In [17]:
webcam=cv2.VideoCapture(0)
c=0
while True:
    (_,im)=webcam.read()
    gray=cv2.cvtColor(im,cv2.COLOR_BGR2GRAY)
    faces=face_cascade.detectMultiScale(gray,1.3,4)
    for (x,y,w,h) in faces:
        cv2.rectangle(im,(x,y),(x+w,y+h),(255,0,0),2)
        face=gray[y:y+h,x:x+w]
        face_resize=cv2.resize(face,(width,height))
        prediction=model.predict(face_resize)
        cv2.rectangle(im,(x,y),(x+w,y+h),(0,255,0))
        if prediction[1]<800:
            cv2.putText(im,'%s - %.0f' % (names[prediction[0]],prediction[1]),(x-10,y-10),cv2.FONT_HERSHEY_PLAIN,1,(255,0,0))
            print(names[prediction[0]])
            c=0
        else:
            c+=1
            cv2.putText(im,'Unknown',(x-10,y-10),cv2.FONT_HERSHEY_PLAIN,1,(255,0,0))
            if(cnt>100):
                print("Unknown Person")
                cv2.imwrite("input.jpg",im)
                c=0
    cv2.imshow('opencv',im)
    key=cv2.waitKey(10)
    if key == 27:
        break
webcam.release()
cv2.destroyALLWindows()
                

shanmukh
shanmukh
shanmukh
shanmukh
dhoni
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shan

shanmukh
dhoni
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shan

shanmukh
shanmukh
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
dhoni
shanmukh
dhoni
shanmukh
dhoni
shanmukh
shanmukh
shanmukh
dhoni
dhoni
dhoni
dhoni
dhoni
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
dhoni
shanmukh
shanmukh
dhoni
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
dhoni
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
dhoni
dhoni
dhoni
dhoni
dhoni
dhoni
dhoni
dhoni
dhoni
dhoni
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shan

shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
s

shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
s

shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
s

shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
shanmukh
s

error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-wwma2wne\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
